openapi: 3.0.2
info:
  title: Workmate test task
  description: Task management API
  version: 1.0.0

servers:
  - url: 'http://localhost:8080'

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: Tasks not found

    post:
      summary: Create a task
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"



  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        '400':
          description: Bad request (invalid task ID)
        '404':
          description: Not found

    delete:
      summary: Delete a task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '400':
          description: Bad request
        '404':
          description: Not found



components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        created_at:
          type: string
          format: date-time
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        duration:
          type: string
          example: 1m30s
        result:
          type: string
        errorMsg:
          type: string


